services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/api
    ports:
      - 3000:3000
  expo-app:
    build:
      context: ./free-go
      dockerfile: Dockerfile
    volumes:
      - ./free-go:/usr/src/free-go
    ports:
      - 8081:8081
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: MySecurePwd
      MYSQL_DATABASE: freego
      MYSQL_USER: myuser
      MYSQL_PASSWORD: monpassword
    ports:
      - 3306:3306
  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: myuser
      PMA_PASSWORD: monpassword
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
