CREATE TABLE IF NOT EXISTS todoListTask (
	id INT AUTO_INCREMENT PRIMARY KEY,
	todoListId INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	dueDate TIMESTAMP NULL,
	isComplete BOOLEAN NOT NULL DEFAULT FALSE,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (todoListId) REFERENCES todoList(id) ON DELETE CASCADE
)