CREATE TABLE IF NOT EXISTS user_session (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT NOT NULL,
	token VARCHAR(255) NOT NULL,
	expiresAt TIMESTAMP NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
)