CREATE TABLE IF NOT EXISTS calendarEvent (
    id INT AUTO_INCREMENT PRIMARY KEY,
    calendarId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    descritpion TEXT,
    startDate TIMESTAMP,
    endDate TIMESTAMP,
    isRecurrent BOOLEAN NOT NULL DEFAULT FALSE,
    color VARCHAR(255) NOT NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    FOREIGN KEY (calendarId) REFERENCES calendar(id)
)