CREATE TABLE IF NOT EXISTS user_notification_token (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT NOT NULL,
	provider ENUM('android') NOT NULL DEFAULT 'android',
	token VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
)