CREATE TABLE IF NOT EXISTS family_members (
	id INT PRIMARY KEY AUTO_INCREMENT,
	familyId INT NOT NULL,
	userId INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (familyId) REFERENCES family(id) ON DELETE CASCADE,
	FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
	UNIQUE (familyId, userId)
);