export const Colors = {
  light: {
    fridge: "#FFD700",
    background: "#F7FAFA",
    elementBackground: "#FFF",
    shelf: "#D3D3D3",
    handleGray: "#C0C0C0",
    primary: "#F5C754",
    secondary: "#E3E8F2",
    primaryText: "#11181C",
    fixedPrimaryText: "#11181C",
    secondaryText: "#9C854A",
    placeHolderText: "#666",
    inactive: "#BDBDBD",
    danger: "#D32F2F",
    logo: "#11181C",
    logoBackground: "#e4eaf1",
    listBackground: "#FFFFFF",
    progressBarCompleted: "#149414",
    inputBorder: "#DDD", 
    icon: "#666",
    error: "#D32F2F",
    settingsBackground: "light-grey",
  },

  dark: {
    fridge: "#F5C754",
    background: "#121C24",
    elementBackground: "#29384D",
    shelf: "#767676",
    handleGray: "#C0C0C0",
    primary: "#F5C754",
    secondary: "#E3E8F2",
    primaryText: "#F7FAFA",
    fixedPrimaryText: "#11181C",
    secondaryText: "#9C854A",
    placeHolderText: "#AAA",
    inactive: "#BDBDBD",
    danger: "#FF3B30",
    logo: "#11181C",
    logoBackground: "#F5C754",
    listBackground: "#FFFFFF",
    progressBarCompleted: "#149414",
    inputBorder: "#3C4A5A",
    icon: "#AAA",
    error: "#FF3B30",
    settingsBackground: "dark-grey",

  },
};
