export const Colors = {
    light: {
      fridge: "#FFD700",
      background: "#F7FAFA",
      elementBackground: "#FFF",
      handleGray: '#C0C0C0',
      primary: "#F5C754",
      secondary: "#E3E8F2",
      primaryText: "#11181C",
      secondaryText: "#9C854A",
      placeHolderText: "#666",
      inactive: "#BDBDBD",
      danger: "#D32F2F",
      logo: "#11181C",
      logoBackground: "#e4eaf1",
      listBackground: "#FFFFFF",
      progressBarCompleted: "#149414",
    },
  
    dark: {
      fridge: "#FFD700",
      background: "#F7FAFA",
      elementBackground: "#FFF",
      handleGray: '#C0C0C0',
      primary: "#F5C754",
      secondary: "#E3E8F2",
      primaryText: "#11181C",
      secondaryText: "#9C854A",
      placeHolderText: "#666",
      inactive: "#BDBDBD",
      danger: "#D32F2F",
      logo: "#11181C",
      logoBackground: "#e4eaf1",
      listBackground: "#FFFFFF",
      progressBarCompleted: "#149414",
    },
};
