export const Colors = {
    light: {
      fridge: "#FFD700",
      background: "#F7FAFA",
      elementBackground: "#FFF",
      handleGray: '#C0C0C0',
      primary: "#F5C754",
      primaryText: "#11181C",
      secondaryText: "#797e8a",
      danger: "#D32F2F",
      logo: "#11181C",
      logoBackground: "#e4eaf1",
      listBackground: "#FFFFFF",
      progressBarCompleted: "#149414",
      modalBackground: "rgba(0, 0, 0, 0.5)",
    },
  
    dark: {
      fridge: "#FFD700",
      background: "#F7FAFA",
      elementBackground: "#FFF",
      handleGray: '#C0C0C0',
      primary: "#F5C754",
      primaryText: "#11181C",
      secondaryText: "#BDBDBD",
      danger: "#D32F2F",
      logo: "#11181C",
      logoBackground: "#e4eaf1",
      listBackground: "#FFFFFF",
      progressBarCompleted: "#149414",
      modalBackground: "rgba(0, 0, 0, 0.5)",
    },
};
