name: npm audit

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
  
jobs:
  npm-audit-fix:
    strategy:
      matrix:
        folder: [api]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - 
        name: npm audit fix
        uses: hugoheml/npm-audit-fix-action@v7
        with:
          npm_args: --force
          assignees: hugoheml
          commit_title: 'build(deps): npm audit fix in ${{ matrix.folder }}'
          path: ${{ matrix.folder }}
